export const GAME_CONFIG = {
    FREE_SPINS: 5,
    BET: 10,
    SPIN_SCENARIOS: [
        {
            grid: [
                ['ruby', 'topaz', 'crown', 'amethyst', 'crown'],
                ['emerald', 'sapphire', 'hourglass', 'ruby', 'scatter'],
                ['ruby', 'topaz', 'crown', 'ring', 'cup'],
                ['scatter', 'emerald', 'cup', 'hourglass', 'ruby'],
                ['hourglass', 'amethyst', 'sapphire', 'ring', 'cup'],
                ['crown', 'topaz', 'crown', 'amethyst', 'ring'],
            ],
            winCombo: null,
            win: 0,
        },
        {
            grid: [
                ['crown', 'topaz', 'crown', 'amethyst', 'ring'],
                ['emerald', 'sapphire', 'hourglass', 'ruby', 'crown'],
                ['ruby', 'ring', 'amethyst', 'topaz', 'cup'],
                ['scatter', 'emerald', 'cup', 'hourglass', 'scatter'],
                ['amethyst', 'crown', 'sapphire', 'ring', 'amethyst'],
                ['ruby', 'sapphire', 'emerald', 'hourglass', 'topaz'],
            ],
            winCombo: null,
            win: 0,
        },
        {
            grid: [
                ['ring', 'ring', 'ring', 'ring', 'ring'],
                ['ring', 'ring', 'ring', 'ring', 'ring'],
                ['ring', 'ring', 'ring', 'ring', 'ring'],
                ['ring', 'ring', 'ring', 'ring', 'ring'],
                ['ring', 'ring', 'ring', 'ring', 'ring'],
                ['ring', 'ring', 'ring', 'ring', 'ring'],
            ],
            winCombo: [
                [
                    [0, 0],
                    [0, 1],
                    [0, 2],
                    [0, 3],
                    [0, 4],
                ],
                [
                    [1, 0],
                    [1, 1],
                    [1, 2],
                    [1, 3],
                    [1, 4],
                ],
                [
                    [2, 0],
                    [2, 1],
                    [2, 2],
                    [2, 3],
                    [2, 4],
                ],
                [
                    [3, 0],
                    [3, 1],
                    [3, 2],
                    [3, 3],
                    [3, 4],
                ],
                [
                    [4, 0],
                    [4, 1],
                    [4, 2],
                    [4, 3],
                    [4, 4],
                ],
                [
                    [5, 0],
                    [5, 1],
                    [5, 2],
                    [5, 3],
                    [5, 4],
                ],
            ],
            win: 1000,
        },
        {
            grid: [
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
                ['scatter', 'scatter', 'scatter', 'scatter', 'scatter'],
            ],
            winCombo: [
                [
                    [0, 0],
                    [0, 1],
                    [0, 2],
                    [0, 3],
                    [0, 4],
                ],
                [
                    [1, 0],
                    [1, 1],
                    [1, 2],
                    [1, 3],
                    [1, 4],
                ],
                [
                    [2, 0],
                    [2, 1],
                    [2, 2],
                    [2, 3],
                    [2, 4],
                ],
                [
                    [3, 0],
                    [3, 1],
                    [3, 2],
                    [3, 3],
                    [3, 4],
                ],
                [
                    [4, 0],
                    [4, 1],
                    [4, 2],
                    [4, 3],
                    [4, 4],
                ],
                [
                    [5, 0],
                    [5, 1],
                    [5, 2],
                    [5, 3],
                    [5, 4],
                ],
            ],
            win: 1500,
        },
    ],
} as const
